github_key: "key"
github_secret: "key"

twitter_key: "key"
twitter_secret: "key"

facebook_key: "key"
facebook_secret: "key"

aksimet_key: "key"
aksimet_url: "http://nerdnews"

delayed_job_username: "username"
delayed_job_password: "password"

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
secret_token: "Your secret token"
